# Generated by Django 5.0.4 on 2024-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
