# Generated by Django 5.0.4 on 2024-05-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='page_data',
            new_name='sign_data',
        ),
    ]
