# Generated by Django 5.0.4 on 2024-05-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_rename_page_data_document_sign_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sign',
        ),
    ]
