# Generated by Django 5.0.4 on 2024-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_remove_document_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sign_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
