# Generated by Django 5.0.4 on 2024-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_alter_document_sign_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sign_data',
            field=models.JSONField(default=dict),
        ),
    ]
